### ISSUE TITLE
Requirements check failed for JDK 8 ('1.8.*')! Detected version: 11.0.4

### ISSUE THREAD

**Issue by tango4567** [tango4567/solutions#17]
```
> cordova build android --release
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/home/username/Android/Sdk/ (recommended setting)
ANDROID_HOME=/home/username/Android/Sdk/ (DEPRECATED)
Requirements check failed for JDK 8 ('1.8.*')! Detected version: 11.0.4
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.
```

**Comment by voltumna** [comment]
Hi All, I have the same issue, any way to resolve this? 

cordova build android --release
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/home/mau/Android/Sdk (recommended setting)
ANDROID_HOME=/home/mau/Android/Sdk/tools (DEPRECATED)
Using Android SDK: /home/mau/Android/Sdk
Requirements check failed for JDK 8 ('1.8.*')! Detected version: 11.0.8
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.

thanks

**Comment by tango4567** [comment]
Hi @voltumna 
First, you need to check the JDK 8 version is installed or not. 
If  JDK 8 version is installed then you need set as it as the default JDK version. 
Which is explained in this video [How to change JDK version](https://youtu.be/lx3Ca2hH6fc)
For changing the JDK version I request you to please use the following command:
**Check default version** `java -version ` 
**Change Default version** `sudo update-alternatives --config java `
Hope it will you.

**Comment by voltumna** [comment]
Thank you @tango4567 , I was able indeed to change that as you mentioned, but it is just weird that cordova would complain about that: 11.0.8 is the one that is used by Android Studio at the moment. 
but hey, I did manage to do it and it works, 

thanks

**Comment by tango4567** [comment]
I'm closing this issue
For More Visit: [Requirements check failed for JDK 8 ('1.8.*')! Detected version: 11.0.4 ubuntu](https://youtu.be/lx3Ca2hH6fc)
