### ISSUE TITLE
Error mounting /dev/sdb1 at /media/

### ISSUE THREAD

**Issue by tango4567** [tango4567/solutions#26]
Source: [Solution](https://askubuntu.com/questions/586308/error-mounting-dev-sdb1-at-media-on-ubuntu-14-04-lts)
Before that check your partition name by running 
`lsblk`
open terminal with `Ctrl`+`Alt`+`T` and run
`sudo ntfsfix /dev/sdb1`

**Comment by MohamedAta575** [comment]
@tango4567  
typin: Refusing to operate on read-write mounted device /dev/sda.

**Comment by pixel-snjy** [comment]
superb solution for a person who switch from Windows towards Linux.

**Comment by AmirHaytham** [comment]
It worked perfectly, thankx a lot.
