### ISSUE TITLE
Push declined due to email privacy restrictions

### ISSUE THREAD

**Issue by tango4567** [tango4567/solutions#9]
![git](https://user-images.githubusercontent.com/2922986/53482455-3aade300-3aa5-11e9-824c-b3a03dbce64a.png)

**Comment by tango4567** [comment]
**Solutions**
Go to [email settings ](https://github.com/settings/emails)and find your unique ID
```
git config --global user.email "ID+tango4567@users.noreply.github.com"
git rebase -i
git commit --amend --reset-author
git rebase --continue
git push
```

**Comment by musixsterd005** [comment]
@tango4567 when I do git rebase -i a colored screen opens up for editing.

**Comment by tango4567** [comment]
@musixsterd005 can you share a screenshot with some more details so we can try to understand what was the exact issue and try to figure solutions for that.
